<?php

declare(strict_types=1);

namespace Tests\Architect;

use Tests\TestCase;
use Tests\Traits\CreatesBlogs;
use Coeliac\Common\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use JPeters\Architect\TestHelpers\Traits\LogsInUsers;

class TagManagerApiCallTest extends TestCase
{
    use RefreshDatabase;
    use CreatesBlogs;
    use LogsInUsers;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->logIn(factory(User::class)->create(['email' => 'jamie@jamie-peters.co.uk']));

        $this->createBlogTag(['tag' => 'foo']);
        $this->createBlogTag(['tag' => 'baz']);
        $this->createBlogTag(['tag' => 'foobar']);
    }

    /** @test */
    public function itLooksUpValues()
    {
        $request = $this->post('/cs-adm/api/external/tag-manager/search', [
            'tagSource' => 'blogTags',
            'searchTerm' => 'foo',
        ]);

        $request->assertStatus(200)
            ->assertSee('foo')
            ->assertSee('foobar')
            ->assertDontSee('baz');
    }
}
