<?php

declare(strict_types=1);

namespace Tests\Feature\Common\Contact;

use Tests\TestCase;
use Coeliac\Common\Mail\ContactUs;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Event;
use Illuminate\Foundation\Testing\WithFaker;
use Coeliac\Common\Events\ContactFormSubmitted;
use Illuminate\Foundation\Testing\RefreshDatabase;

class
ContactTest extends TestCase
{
    use RefreshDatabase;
    use WithFaker;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->setUpFaker();
    }

    /** @test */
    public function itLoadsThePage()
    {
        $this->get('/contact')
            ->assertStatus(200)
            ->assertSee('<contact-trigger :open="true" redirect="/"></contact-trigger>', false);
    }

    /** @test */
    public function itErrorsWithoutAName()
    {
        $this->makeRequest(['name' => null])->assertStatus(422);
    }

    /** @test */
    public function itErrorsWithoutAnEmail()
    {
        $this->makeRequest(['email' => null])->assertStatus(422);
    }

    /** @test */
    public function itErrorsWithAnInvalidEmail()
    {
        $this->makeRequest(['email' => 'foo'])->assertStatus(422);
    }

    /** @test */
    public function itErrorsWithoutASubject()
    {
        $this->makeRequest(['subject' => null])->assertStatus(422);
    }

    /** @test */
    public function itErrorsWithoutAMessage()
    {
        $this->makeRequest(['message' => null])->assertStatus(422);
    }

    /** @test */
    public function itReturnsSuccessfulWhenValidDateIsSent()
    {
        Event::fake();
        $this->makeRequest()->assertStatus(200);
    }

    /** @test */
    public function itDispatchesAnEventWhenTheFormIsSubmitted()
    {
        Event::fake();
        $this->makeRequest();

        Event::assertDispatched(ContactFormSubmitted::class);
    }

    /** @test */
    public function itSendsAnEmailWhenTheFormIsSubmitted()
    {
        Mail::fake();

        $this->makeRequest();

        Mail::assertSent(ContactUs::class);
    }

    protected function makeRequest($params = [])
    {
        return $this->post('/api/contact', array_merge([
            'name' => $this->faker->name,
            'email' => $this->faker->email,
            'subject' => $this->faker->sentence,
            'message' => $this->faker->paragraph,
        ], $params));
    }
}
