import Vue from 'vue';

const CoeliacIcon = () => import("./Components/CoeliacIcon");
const MobileNav = () => import("./Components/MobileNav");
const HeaderSearch = () => import("./Components/HeaderSearch");
const HomepageHeros = () => import("./Components/HomepageHeros");
const LinkButton = () => import("./Components/LinkButton");
const TopBar = () => import("./Components/TopBar");
const NumberCountUp = () => import("./Components/NumberCountUp");
const FooterNewsletter = () => import("./Components/FooterNewsletter");
const Breadcrumbs = () => import("./Components/Breadcrumbs");
const ModuleListIndex = () => import("./Components/ModuleListIndex");
const Accordion = () => import("./Components/Accordion");
const Widget = () => import("./Components/Widget");
const NewsletterSignup = () => import("./Components/Widgets/NewsletterSignup");
const BlogSearch = () => import("./Components/Widgets/BlogSearch");
const CommentForm = () => import("./Components/CommentForm");
const RecipeImage = () => import("./Components/RecipeImage");
const RecipeSearch = () => import("./Components/Widgets/RecipeSearch");
const Tabs = () => import("./Components/Tabs");
const Tab = () => import("./Components/Tab");
const WhereToEatMap = () => import("./Components/WhereToEatMap");
const WhereToEatList = () => import("./Components/WhereToEatList");
const StaticMap = () => import("./Components/StaticMap");
const Stars = () => import("./Components/Stars");
const WhereToEatPlaceRequestForm = () => import("./Components/WhereToEatPlaceRequestForm");
const ReviewSearch = () => import("./Components/Widgets/ReviewSearch");
const ArticleImage = () => import("./Components/ArticleImage");
const ContactTrigger = () => import("./Components/ContactTrigger");
const WhereToEatSearch = () => import("./Components/Widgets/WhereToEatSearch");
const AddBasketTrigger = () => import("./Components/AddBasketTrigger");
const BasketHeaderWidget = () => import("./Components/BasketHeaderWidget");
const BasketSideBar = () => import("./Components/BasketSideBar");
const BasketQuickLink = () => import("./Components/BasketQuickLink");
const ProductImages = () => import("./Components/ProductImages");
const ProductAddToBasket = () => import("./Components/ProductAddToBasket");
const BasketPage = () => import("./Components/BasketPage");
const BasketQuantitySwitcher = () => import("./Components/BasketQuantitySwitcher");
const FullPageLoader = () => import("./Components/FullPageLoader");
const QuickSearch = () => import("./Components/QuickSearch");
const Announcement = () => import("./Components/Announcement");
const PopupCta = () => import("./Components/PopupCta");
const GoogleAd = () => import('./Components/GoogleAd');
const WhereToEatQuickSearch = () => import('./Components/WhereToEatQuickSearch')

Vue.component('accordion', Accordion);
Vue.component('add-basket-trigger', AddBasketTrigger);
Vue.component('announcement', Announcement);
Vue.component('article-image', ArticleImage);
Vue.component('basket-header-widget', BasketHeaderWidget);
Vue.component('basket-quick-link', BasketQuickLink);
Vue.component('basket-page', BasketPage);
Vue.component('basket-quantity-swticher', BasketQuantitySwitcher);
Vue.component('basket-sidebar', BasketSideBar);
Vue.component('breadcrumbs', Breadcrumbs);
Vue.component('coeliac-icon', CoeliacIcon);
Vue.component('coeliac-home-heros', HomepageHeros);
Vue.component('comment-form', CommentForm);
Vue.component('contact-trigger', ContactTrigger);
Vue.component('footer-newsletter', FooterNewsletter);
Vue.component('full-page-loader', FullPageLoader);
Vue.component('google-ad', GoogleAd);
Vue.component('header-search', HeaderSearch);
Vue.component('link-button', LinkButton);
Vue.component('mobile-nav', MobileNav);
Vue.component('module-list-index', ModuleListIndex);
Vue.component('number-counter', NumberCountUp);
Vue.component('popup-cta', PopupCta);
Vue.component('product-add-basket', ProductAddToBasket);
Vue.component('product-images', ProductImages);
Vue.component('quick-search', QuickSearch);
Vue.component('recipe-image', RecipeImage);
Vue.component('static-map', StaticMap);
Vue.component('stars', Stars);
Vue.component('tab', Tab);
Vue.component('tabs', Tabs);
Vue.component('top-bar', TopBar);
Vue.component('wheretoeat-list', WhereToEatList);
Vue.component('wheretoeat-map', WhereToEatMap);
Vue.component('wheretoeat-place-request-form', WhereToEatPlaceRequestForm);
Vue.component('wheretoeat-quick-search', WhereToEatQuickSearch)
Vue.component('widget', Widget);

Vue.component('widget-blog-search', BlogSearch);
Vue.component('widget-newsletter-signup', NewsletterSignup);
Vue.component('widget-recipe-search', RecipeSearch);
Vue.component('widget-review-search', ReviewSearch);
Vue.component('widget-wheretoeat-search', WhereToEatSearch);
