import Vue from 'vue'
import CoeliacIcon from "./Components/CoeliacIcon";
import MobileNav from "./Components/MobileNav";
import HeaderSearch from "./Components/HeaderSearch";
import CoeliacHomeHeader from "./Components/HomepageHeros";
import LinkButton from "./Components/LinkButton";
import TopBar from "./Components/TopBar";
import CoeliacNav from "./Components/CoeliacNav";
import NumberCountUp from "./Components/NumberCountUp";
import FooterNewsletter from "./Components/FooterNewsletter";
import Breadcrumbs from "./Components/Breadcrumbs";
import ModuleListIndex from "./Components/ModuleListIndex";
import Pagination from "./Components/Pagination";
import Loader from "./Components/Loader";
import ModuleListItem from "./Components/ModuleListItem";
import ModuleListTopBar from "./Components/ModuleListTopBar";
import ModuleFilterSlider from "./Components/ModuleFilterSlider";
import BlogFilter from "./Components/Filters/BlogFilter";
import Accordion from "./Components/Accordion";
import Widget from "./Components/Widget";
import NewsletterSignup from "./Components/Widgets/NewsletterSignup";
import BlogSearch from "./Components/Widgets/BlogSearch";
import CommentForm from "./Components/CommentForm";
import FormInput from "./Components/Forms/FormInput";
import FormTextarea from "./Components/Forms/FormTextarea";
import RecipeFilter from "./Components/Filters/RecipeFilter";
import RecipeImage from "./Components/RecipeImage";
import RecipeSearch from "./Components/Widgets/RecipeSearch";
import Tabs from "./Components/Tabs";
import Tab from "./Components/Tab";
import WhereToEatMap from "./Components/WhereToEatMap";
import WhereToEatList from "./Components/WhereToEatList";
import WhereToEatNationwide from "./Components/WhereToEatNationwide";
import WhereToEatReviewButton from "./Components/WhereToEatReviewButton";
import WhereToEatFeatures from "./Components/WhereToEatFeatures";
import WhereToEatEatery from "./Components/WhereToEatEatery";
import Modal from "./Components/Modal";
import StaticMap from "./Components/StaticMap";
import DynamicMap from "./Components/DynamicMap";
import WhereToEatAttraction from "./Components/WhereToEatAttraction";
import WhereToEatHotel from "./Components/WhereToEatHotel";
import Stars from "./Components/Stars";
import WhereToEatRatings from "./Components/WhereToEatRatings";
import WhereToEatCreateRating from "./Components/WhereToEatCreateRating";
import FormSelect from "./Components/Forms/FormSelect";
import WhereToEatPlaceRequestForm from "./Components/WhereToEatPlaceRequestForm";
import ReviewsFilter from "./Components/Filters/ReviewsFilter";
import ReviewSearch from "./Components/Widgets/ReviewSearch";
import ArticleImage from "./Components/ArticleImage";
import ContactUs from "./Components/ContactForm";
import ContactTrigger from "./Components/ContactTrigger";
import WhereToEatSearch from "./Components/Widgets/WhereToEatSearch";
import AddBasketTrigger from "./Components/AddBasketTrigger";
import BasketHeaderWidget from "./Components/BasketHeaderWidget";
import BasketSideBar from "./Components/BasketSideBar";
import BasketQuickLink from "./Components/BasketQuickLink";
import ProductImages from "./Components/ProductImages";
import ProductAddToBasket from "./Components/ProductAddToBasket";
import ProductQuantity from "./Components/ProductQuantity";
import BasketPage from "./Components/BasketPage";
import BasketQuantitySwitcher from "./Components/BasketQuantitySwitcher";
import BasketPageTotals from "./Components/BasketPageTotals";
import BasketCheckoutWrapper from "./Components/BasketCheckoutWrapper";
import UserDetails from "./Components/Checkout/UserDetails";
import ShippingDetails from "./Components/Checkout/ShippingDetails";
import PaymentDetails from "./Components/Checkout/PaymentDetails";
import FormOption from "./Components/Forms/FormOption";
import StripeCheckout from "./Components/StripeCheckout";
import FullPageLoader from "./Components/FullPageLoader";
import PayPalCheckout from "./Components/PayPalCheckout";
import QuickSearch from "./Components/QuickSearch";
import FormCheckbox from "./Components/Forms/FormCheckbox";
import BlogResult from "./Components/Search/BlogResult";
import ReviewResult from "./Components/Search/ReviewResult";
import RecipeResult from "./Components/Search/RecipeResult";
import EateryResult from "./Components/Search/EateryResult";
import ShopProductResult from "./Components/Search/ShopProductResult";
import Announcement from "./Components/Announcement";
import PopupCta from "./Components/PopupCta";
import BasketDiscountModal from "./Components/BasketDiscountModal";

Vue.component('accordion', Accordion);
Vue.component('add-basket-trigger', AddBasketTrigger);
Vue.component('announcement', Announcement);
Vue.component('article-image', ArticleImage);
Vue.component('basket-header-widget', BasketHeaderWidget);
Vue.component('basket-quick-link', BasketQuickLink);
Vue.component('basket-page', BasketPage);
Vue.component('basket-quantity-swticher', BasketQuantitySwitcher);
Vue.component('basket-sidebar', BasketSideBar);
Vue.component('breadcrumbs', Breadcrumbs);
Vue.component('coeliac-icon', CoeliacIcon);
Vue.component('coeliac-home-header', CoeliacHomeHeader);
Vue.component('comment-form', CommentForm);
Vue.component('contact-trigger', ContactTrigger);
Vue.component('footer-newsletter', FooterNewsletter);
Vue.component('full-page-loader', FullPageLoader);
Vue.component('header-search', HeaderSearch);
Vue.component('link-button', LinkButton);
Vue.component('mobile-nav', MobileNav);
Vue.component('module-list-index', ModuleListIndex);
Vue.component('number-counter', NumberCountUp);
Vue.component('popup-cta', PopupCta);
Vue.component('product-add-basket', ProductAddToBasket);
Vue.component('product-images', ProductImages);
Vue.component('quick-search', QuickSearch);
Vue.component('recipe-image', RecipeImage);
Vue.component('static-map', StaticMap);
Vue.component('stars', Stars);
Vue.component('tab', Tab);
Vue.component('tabs', Tabs);
Vue.component('top-bar', TopBar);
Vue.component('wheretoeat-create-rating', WhereToEatCreateRating);
Vue.component('wheretoeat-list', WhereToEatList);
Vue.component('wheretoeat-map', WhereToEatMap);
Vue.component('wheretoeat-place-request-form', WhereToEatPlaceRequestForm);
Vue.component('wheretoeat-ratings', WhereToEatRatings);
Vue.component('widget', Widget);

Vue.component('wheretoeat-place-attraction', WhereToEatAttraction);
Vue.component('wheretoeat-place-eatery', WhereToEatEatery);
Vue.component('wheretoeat-place-hotel', WhereToEatHotel);
Vue.component('wheretoeat-place-nationwide', WhereToEatNationwide);

Vue.component('wheretoeat-list-features', WhereToEatFeatures);
Vue.component('wheretoeat-list-reviews', WhereToEatReviewButton);

Vue.component('form-checkbox', FormCheckbox);
Vue.component('form-input', FormInput);
Vue.component('form-option', FormOption);
Vue.component('form-select', FormSelect);
Vue.component('form-textarea', FormTextarea);

Vue.component('blogs-filter', BlogFilter);
Vue.component('recipes-filter', RecipeFilter);
Vue.component('reviews-filter', ReviewsFilter);

Vue.component('widget-blog-search', BlogSearch);
Vue.component('widget-newsletter-signup', NewsletterSignup);
Vue.component('widget-recipe-search', RecipeSearch);
Vue.component('widget-review-search', ReviewSearch);
Vue.component('widget-wheretoeat-search', WhereToEatSearch);

Vue.component('basket-checkout-user-details', UserDetails);
Vue.component('basket-checkout-shipping-details', ShippingDetails);
Vue.component('basket-checkout-payment-details', PaymentDetails);

Vue.component('stripe-checkout', StripeCheckout);
Vue.component('paypal-checkout', PayPalCheckout);

Vue.component('search-blog-result', BlogResult);
Vue.component('search-eatery-result', EateryResult);
Vue.component('search-recipe-result', RecipeResult);
Vue.component('search-review-result', ReviewResult);
Vue.component('search-shop-product-result', ShopProductResult);
