import Vue from 'vue';

const CoeliacIcon = () => import("./Components/CoeliacIcon" /* webpackChunkName: "preload-coeliac-icon" */);
const MobileNav = () => import("./Components/MobileNav" /* webpackChunkName: "preload-mobile-nav" */);
const HeaderSearch = () => import("./Components/HeaderSearch" /* webpackChunkName: "preload-header-search" */);
const HomepageHeros = () => import("./Components/HomepageHeros" /* webpackChunkName: "prefetch-home-heros" */);
const LinkButton = () => import("./Components/LinkButton" /* webpackChunkName: "prefetch-link-button" */);
const TopBar = () => import("./Components/TopBar" /* webpackChunkName: "preload-top-bar" */);
const NumberCountUp = () => import("./Components/NumberCountUp" /* webpackChunkName: "prefetch-number-count" */);
const FooterNewsletter = () => import("./Components/FooterNewsletter" /* webpackChunkName: "preload-footer-newsletter" */);
const Breadcrumbs = () => import("./Components/Breadcrumbs" /* webpackChunkName: "prefetch-breadcrumbs" */);
const ModuleListIndex = () => import("./Components/ModuleListIndex" /* webpackChunkName: "prefetch-module-list-index" */);
const Accordion = () => import("./Components/Accordion" /* webpackChunkName: "prefetch-accordion" */);
const Widget = () => import("./Components/Widget" /* webpackChunkName: "prefetch-widget" */);
const NewsletterSignup = () => import("./Components/Widgets/NewsletterSignup" /* webpackChunkName: "prefetch-newsletter-signup" */);
const BlogSearch = () => import("./Components/Widgets/BlogSearch" /* webpackChunkName: "prefetch-blog-search" */);
const CommentForm = () => import("./Components/CommentForm" /* webpackChunkName: "prefetch-comment-form" */);
const RecipeImage = () => import("./Components/RecipeImage" /* webpackChunkName: "prefetch-recipe-image" */);
const RecipeSearch = () => import("./Components/Widgets/RecipeSearch" /* webpackChunkName: "prefetch-recipe-search" */);
const Tabs = () => import("./Components/Tabs" /* webpackChunkName: "prefetch-tabs" */);
const Tab = () => import("./Components/Tab" /* webpackChunkName: "prefetch-tab" */);
const WhereToEatMap = () => import("./Components/WhereToEatMap" /* webpackChunkName: "prefetch-wte-map" */);
const WhereToEatList = () => import("./Components/WhereToEatList" /* webpackChunkName: "prefetch-wte-list" */);
const StaticMap = () => import("./Components/StaticMap" /* webpackChunkName: "prefetch-static-map" */);
const Stars = () => import("./Components/Stars" /* webpackChunkName: "prefetch-stars" */);
const WhereToEatPlaceRequestForm = () => import("./Components/WhereToEatPlaceRequestForm" /* webpackChunkName: "prefetch-wte-place-request" */);
const ReviewSearch = () => import("./Components/Widgets/ReviewSearch" /* webpackChunkName: "prefetch-review-search" */);
const ArticleImage = () => import("./Components/ArticleImage" /* webpackChunkName: "prefetch-article-image" */);
const ContactTrigger = () => import("./Components/ContactTrigger" /* webpackChunkName: "prefetch-contact-trigger" */);
const WhereToEatSearch = () => import("./Components/Widgets/WhereToEatSearch" /* webpackChunkName: "prefetch-wte-search" */);
const AddBasketTrigger = () => import("./Components/AddBasketTrigger" /* webpackChunkName: "prefetch-add-basket-trigger" */);
const BasketHeaderWidget = () => import("./Components/BasketHeaderWidget" /* webpackChunkName: "prefetch-basket-header-widget" */);
const BasketSideBar = () => import("./Components/BasketSideBar" /* webpackChunkName: "prefetch-basket-sidebar" */);
const BasketQuickLink = () => import("./Components/BasketQuickLink" /* webpackChunkName: "prefetch-basket-quick-link" */);
const ProductImages = () => import("./Components/ProductImages" /* webpackChunkName: "prefetch-product-images" */);
const ProductAddToBasket = () => import("./Components/ProductAddToBasket" /* webpackChunkName: "prefetch-product-add-basket" */);
const BasketPage = () => import("./Components/BasketPage" /* webpackChunkName: "prefetch-basket-page" */);
const BasketQuantitySwitcher = () => import("./Components/BasketQuantitySwitcher" /* webpackChunkName: "prefetch-basket-quantity-switcher" */);
const FullPageLoader = () => import("./Components/FullPageLoader" /* webpackChunkName: "prefetch-page-loader" */);
const QuickSearch = () => import("./Components/QuickSearch" /* webpackChunkName: "preload-quick-search" */);
const Announcement = () => import("./Components/Announcement" /* webpackChunkName: "prefetch-announcements" */);
const PopupCta = () => import("./Components/PopupCta" /* webpackChunkName: "preload-popup-cta" */);
const GoogleAd = () => import('./Components/GoogleAd' /* webpackChunkName: "preload-google-ad" */);
const WhereToEatQuickSearch = () => import('./Components/WhereToEatQuickSearch' /* webpackChunkName: "prefetch-wte-quick-search" */);

Vue.component('accordion', Accordion);
Vue.component('add-basket-trigger', AddBasketTrigger);
Vue.component('announcement', Announcement);
Vue.component('article-image', ArticleImage);
Vue.component('basket-header-widget', BasketHeaderWidget);
Vue.component('basket-quick-link', BasketQuickLink);
Vue.component('basket-page', BasketPage);
Vue.component('basket-quantity-swticher', BasketQuantitySwitcher);
Vue.component('basket-sidebar', BasketSideBar);
Vue.component('breadcrumbs', Breadcrumbs);
Vue.component('coeliac-icon', CoeliacIcon);
Vue.component('coeliac-home-heros', HomepageHeros);
Vue.component('comment-form', CommentForm);
Vue.component('contact-trigger', ContactTrigger);
Vue.component('footer-newsletter', FooterNewsletter);
Vue.component('full-page-loader', FullPageLoader);
Vue.component('google-ad', GoogleAd);
Vue.component('header-search', HeaderSearch);
Vue.component('link-button', LinkButton);
Vue.component('mobile-nav', MobileNav);
Vue.component('module-list-index', ModuleListIndex);
Vue.component('number-counter', NumberCountUp);
Vue.component('popup-cta', PopupCta);
Vue.component('product-add-basket', ProductAddToBasket);
Vue.component('product-images', ProductImages);
Vue.component('quick-search', QuickSearch);
Vue.component('recipe-image', RecipeImage);
Vue.component('static-map', StaticMap);
Vue.component('stars', Stars);
Vue.component('tab', Tab);
Vue.component('tabs', Tabs);
Vue.component('top-bar', TopBar);
Vue.component('wheretoeat-list', WhereToEatList);
Vue.component('wheretoeat-map', WhereToEatMap);
Vue.component('wheretoeat-place-request-form', WhereToEatPlaceRequestForm);
Vue.component('wheretoeat-quick-search', WhereToEatQuickSearch)
Vue.component('widget', Widget);

Vue.component('widget-blog-search', BlogSearch);
Vue.component('widget-newsletter-signup', NewsletterSignup);
Vue.component('widget-recipe-search', RecipeSearch);
Vue.component('widget-review-search', ReviewSearch);
Vue.component('widget-wheretoeat-search', WhereToEatSearch);
