<?php

declare(strict_types=1);

namespace Tests\Feature\Modules\EatingOut\WhereToEat;

use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Coeliac\Modules\EatingOut\WhereToEat\Models\WhereToEatSearch;
use Coeliac\Modules\EatingOut\WhereToEat\Models\WhereToEatSearchTerm;

class WhereToEatSearchRequestTest extends TestCase
{
    use RefreshDatabase;
    use WithFaker;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->setUpFaker();
    }

    protected function makeRequest($params = [])
    {
        return $this->post('/api/wheretoeat/search', array_merge([
            'text' => $this->faker->word,
            'range' => $this->faker->randomElement(['1', '2', '5', '10', '20']),
        ], $params));
    }

    /** @test */
    public function itErrorsIfYouDontIncludeASearchTerm()
    {
        $this->makeRequest(['text' => null])->assertStatus(422);
    }

    /** @test */
    public function itErrorsIfYouDontIncludeARange()
    {
        $this->makeRequest(['range' => null])->assertStatus(422);
    }

    /** @test */
    public function itErrorsIfYouSendAnInvalidRange()
    {
        $this->makeRequest(['range' => 'foo'])->assertStatus(422);
        $this->makeRequest(['range' => 1])->assertStatus(422);
        $this->makeRequest(['range' => '3'])->assertStatus(422);
    }

    /** @test */
    public function itReturnsASuccessWhenAValidRequestIsSent()
    {
        $this->makeRequest()->assertStatus(200);
    }

    /** @test */
    public function itCreatesASearchTermUponAValidRequest()
    {
        $this->assertEmpty(WhereToEatSearchTerm::query()->get());

        $this->makeRequest(['text' => 'Foo', 'range' => '1']);

        $this->assertNotEmpty(WhereToEatSearchTerm::query()->get());

        /** @var WhereToEatSearchTerm $term */
        $term = WhereToEatSearchTerm::query()->first();

        $this->assertEquals('Foo', $term->term);
        $this->assertEquals('1', $term->range);
    }

    /** @test */
    public function itLogsASearchUponAValidRequest()
    {
        $this->assertEmpty(WhereToEatSearch::query()->get());

        $this->makeRequest();

        $this->assertNotEmpty(WhereToEatSearch::query()->get());
    }

    /** @test */
    public function itReturnsTheSearchKeyInTheResponse()
    {
        $request = $this->makeRequest();

        /** @var WhereToEatSearchTerm $term */
        $term = WhereToEatSearchTerm::query()->first();

        $request->assertJson(['search' => $term->key]);
    }
}
