<?php

declare(strict_types=1);

namespace Tests\Feature;

use Tests\TestCase;
use Tests\Traits\CreatesWhereToEat;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Coeliac\Modules\EatingOut\WhereToEat\Models\WhereToEat;

class WhereToEatingRatingsTest extends TestCase
{
    use RefreshDatabase;
    use CreatesWhereToEat;
    use WithFaker;

    /** @var WhereToEat */
    protected $whereToEat;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->whereToEat = $this->createWhereToEat();
    }

    private function makeRequest($params = [])
    {
        return $this->post("api/wheretoeat/{$this->whereToEat->id}/reviews", array_merge([
            'rating' => 5,
            'name' => $this->faker->name,
            'email' => $this->faker->email,
            'comment' => $this->faker->paragraph,
        ], $params));
    }

    /** @test */
    public function it_can_create_ratings()
    {
        $this->withoutExceptionHandling();
        $this->makeRequest()->assertStatus(200)->content();

        $this->assertEquals(1, $this->whereToEat->fresh()->ratings()->count());
    }

    /** @test */
    public function it_is_not_approved_by_default()
    {
        $this->makeRequest();

        $this->assertFalse($this->whereToEat->fresh()->ratings()->first()->approved);
    }

    /** @test */
    public function it_will_only_allow_one_rating_per_ip_address()
    {
        $this->makeRequest()->assertStatus(200);

        $this->assertEquals(1, $this->whereToEat->fresh()->ratings()->count());

        $this->makeRequest()->assertStatus(422)
        ->assertJson(['error' => 'You have already rated this location']);

        $this->assertEquals(1, $this->whereToEat->fresh()->ratings()->count());
    }

    /** @test */
    public function it_approves_empty_ratings()
    {
        $this->makeRequest(['name' => null, 'email' => null, 'comment' => null])
            ->assertStatus(200);

        $this->assertEquals(1, $this->whereToEat->fresh()->ratings()->count());
        $this->assertTrue($this->whereToEat->ratings()->first()->approved);
    }

    /** @test */
    public function it_errors_without_a_rating()
    {
        $this->makeRequest(['rating' => null])->assertStatus(422);

        $this->assertEquals(0, $this->whereToEat->fresh()->ratings()->count());
    }

    /** @test */
    public function it_errors_with_an_invalid_rating()
    {
        $this->makeRequest(['rating' => 'foo'])->assertStatus(422);

        $this->assertEquals(0, $this->whereToEat->fresh()->ratings()->count());
    }

    /** @test */
    public function it_errors_with_a_rating_that_is_lower_than_1()
    {
        $this->makeRequest(['rating' => 0])->assertStatus(422);

        $this->assertEquals(0, $this->whereToEat->fresh()->ratings()->count());

        $this->makeRequest(['rating' => -1])->assertStatus(422);

        $this->assertEquals(0, $this->whereToEat->fresh()->ratings()->count());
    }

    /** @test */
    public function it_errors_with_a_rating_that_is_greater_than_5()
    {
        $this->makeRequest(['rating' => 6])->assertStatus(422);

        $this->assertEquals(0, $this->whereToEat->fresh()->ratings()->count());
    }

    /** @test */
    public function it_errors_without_a_name()
    {
        $this->makeRequest(['name' => null])->assertStatus(422);

        $this->assertEquals(0, $this->whereToEat->fresh()->ratings()->count());
    }

    /** @test */
    public function it_errors_without_a_email()
    {
        $this->makeRequest(['email' => null])->assertStatus(422);

        $this->assertEquals(0, $this->whereToEat->fresh()->ratings()->count());
    }

    /** @test */
    public function it_errors_with_an_invalid_email()
    {
        $this->makeRequest(['email' => 'foo'])->assertStatus(422);

        $this->assertEquals(0, $this->whereToEat->fresh()->ratings()->count());
    }

    /** @test */
    public function it_errors_without_a_comment()
    {
        $this->makeRequest(['comment' => null])->assertStatus(422);

        $this->assertEquals(0, $this->whereToEat->fresh()->ratings()->count());
    }
}
