<?php

declare(strict_types=1);

namespace Tests\Unit\Modules\Members;

use Tests\TestCase;
use Tests\Mocks\UserActivityMock;
use Illuminate\Container\Container;
use Coeliac\Modules\Member\Contracts\UserActivityMonitor;

class ActivityMonitorTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->app->instance(UserActivityMonitor::class, new UserActivityMock());
    }

    /** @test */
    public function itIsRegisteredInTheContainer()
    {
        $this->assertInstanceOf(
            UserActivityMonitor::class,
            Container::getInstance()->make(UserActivityMonitor::class)
        );
    }
}
