@extends('templates.page-single-column')

@section('primary-column')
    <div class="flex flex-col">
        <div class="page-box">
            <h1 class="text-2xl font-coeliac text-center font-semibold leading-tight md:text-left">
                Privacy Policy
            </h1>

            <div class="flex flex-col mt-4 main-body text-sm">
                <ol>
                    <li>
                        <p>
                            Set out below is the Coeliac Sanctuary Privacy Policy, including what data we collect, why
                            we need it, how we use it and protect it, and how we remove it.
                        </p>
                    </li>
                </ol>
                <h2 class="text-xl font-coeliac font-semibold">Coeliac Sanctuary Website</h2>
                <ol start="2">
                    <li>
                        <p>
                            All pages on the Coeliac Sanctuary website use Google Analytics to help us understand how
                            our visitors access and find the Coeliac Sanctuary website. Google Analytics uses "Cookies",
                            which are tiny text files placed on your device so the analytic software can watch what
                            pages you visit and how you got there, the analytics software only tracks your activity on
                            our own website, and does not track you elsewhere.
                        </p>
                    </li>
                    <li>
                        <p>
                            The information generated by the cookie is transmitted securely to Google's Servers where
                            they process it in a way so we can access it on the Google Analytics website, this
                            information Google store may include your IP address, but we do not get access to this
                            information, nor do we have any way to data to an actual person. For more information please
                            see the <a title="Google Privacy Policy" href="https://policies.google.com/privacy"
                                       target="_blank">Google Analytics Privacy Policy</a>.
                        </p>
                    </li>
                    <li>
                        <p>
                            All parts of the Coeliac Sanctuary website are protected by a SSL certificate, which means
                            all data is encrypted as it is transmitted from your browser to our server.
                        </p>
                    </li>
                    <li>
                        <p>
                            Depending on what parts of the website you use, data we may store about you includes, but is
                            not limited to;
                        </p>
                        <ul class="list-none mb-2">
                            <li class="mb-0">
                                <p style="margin-bottom: 0">
                                    IP Address
                                </p>
                            </li>
                            <li class="mb-0">
                                <p style="margin-bottom: 0">
                                    Name
                                </p>
                            </li>
                            <li class="mb-0">
                                <p style="margin-bottom: 0">
                                    Email Address
                                </p>
                            </li>
                            <li class="mb-0">
                                <p style="margin-bottom: 0">
                                    Postal Address
                                </p>
                            </li>
                            <li class="mb-0">
                                <p style="margin-bottom: 0">
                                    Phone Number
                                </p>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <p>
                            For full information on why, how, and where we store your data please see the below sections
                            of this policy.
                        </p>
                    </li>
                </ol>
                <h2 class="text-xl font-coeliac font-semibold">Advertisements</h2>
                <ol start="7">
                    <li>
                        <p>
                            Coeliac Sanctuary use Google AdSense to publish third party advertisements on our websites,
                            we have no control over these ads, the content of them, or the third-party websites they
                            link to. For more information please see the <a title="Google Privacy Policy"
                                                                            href="https://policies.google.com/privacy"
                                                                            target="_blank">Google AdSense Privacy
                                Policy</a>.
                        </p>
                    </li>
                </ol>
                <h2 class="text-xl font-coeliac font-semibold">Competitions</h2>
                <ol start="8">
                    <li>
                        <p>
                            During the course of a competition we store all data provided in our database, upon a
                            competition ending all PERSONAL data will be securely removed after one month, we will
                            however keep anonymised data so we can track the number of entrants in a competition, and in
                            special cases where part of our competition is to leave feedback on the website, or suggest
                            new features for the website, these will be kept as long as deemed necessary, but we will
                            remove any personal information from the feedback or suggestions.
                        </p>
                    </li>
                </ol>
                <h2 class="text-xl font-coeliac font-semibold">Contact Form</h2>
                <ol start="9">
                    <li>
                        <p>
                            All data through our contact form is sent securely to our email address, once the matter has
                            been dealt with the email is permanently deleted.
                        </p>
                    </li>
                </ol>
                <h2 class="text-xl font-coeliac font-semibold">Newsletter</h2>
                <ol start="10">
                    <li>
                        <p>
                            All users have the option to sign up to our free newsletter, you can do this through any
                            page on our website, and you can also choose to do it through our competition pages and
                            shop.
                        </p>
                    </li>
                    <li>
                        <p>
                            The newsletter is strictly opt-in only, and you only need to provide your email, and you
                            can-opt out at any time by pressing the Unsubscribe link at the bottom of each newsletter.
                        </p>
                    </li>
                    <li>
                        <p>
                            Our newsletter is sent no more than once every two weeks, and contains links to our latest
                            or popular blogs, recipes, or reviews.
                        </p>
                    </li>
                    <li>
                        <p>
                            Our newsletter is managed by MailChimp, for more information please see <a
                                title="Mailchimp Privacy Policy" href="https://mailchimp.com/legal/privacy/"
                                target="_blank">MailChimp's Privacy Policy</a>.
                        </p>
                    </li>
                </ol>
                <h2 class="text-xl font-coeliac font-semibold">Place Suggest Form</h2>
                <ol start="14">
                    <li>
                        <p>
                            Any data sent through our Place Request form or through our website or App is stored
                            securely in our Database, when we have checked the suggestion(s) supplied we will mark the
                            Place Request as finished, and within 2 weeks the personal data associated with this request
                            is deleted, but the actual message is retained. This is so we have a data trail and can see
                            how and when places are first suggested to us.
                        </p>
                    </li>
                </ol>
                <h2 class="text-xl font-coeliac font-semibold">Coeliac Sanctuary Shop</h2>
                <ol start="15">
                    <li>
                        <p>
                            Personal data is handled in several ways while using our online Shop
                        </p>
                    </li>
                    <li>
                        <h3 class="text-lg font-coeliac font-semibold">Orders</h3>
                        <ol>
                            <li>
                                <p>
                                    When you make an order in our online shop your name, email address and postal
                                    address are securely stored in our database, we will keep this data securely for at
                                    a minimum of seven (7) years for tax purposes. Your information is stored online in
                                    password protected environments and offline under lock and key. We do NOT, and never
                                    will store any payment information, including, but not limited to, Credit/Debit card
                                    numbers, Expiry dates, CVC numbers and PayPal usernames or Passwords.
                                </p>
                            </li>
                            <li>
                                <p>
                                    ALL payment processing is done through external servers (Stripe, Paypal) and your
                                    payment details do not get transmitted to our own server.
                                </p>
                            </li>
                        </ol>
                    </li>
                    <li>
                        <h3 class="text-lg font-coeliac font-semibold">Baskets</h3>
                        <ol>
                            <li>
                                <p>
                                    When you create a basket your IP address is stored and is used to associate a basket
                                    with your device, so you can access it at any time the basket remains open (1 hour).
                                </p>
                            </li>
                            <li>
                                <p>
                                    We also log all data (excluding payment details) through our basket page, including
                                    when you enter your personal information (Excluding any payment information) - We
                                    only log data so we can identify potential problems with our software if we are
                                    contacted by users who encountered an issue, where users had problems completing
                                    their purchase and any error information returned from the payment provider, and to
                                    identify situations where users filled out the basket details but didn't pay.
                                </p>
                            </li>
                            <li>
                                <p>
                                    All basket logs are stored securely in our database and will be automatically
                                    deleted after 2 weeks.
                                </p>
                            </li>
                        </ol>
                    </li>
                </ol>
                <h2 class="text-xl font-coeliac font-semibold">Third Party Policies</h2>
                <ol start="18">
                    <li>
                        <p>
                            Websites linked from our website are out of our control and we are not responsible for any
                            content, tracking or privacy policies on these websites or services.
                        </p>
                    </li>
                </ol>
                <h2 class="text-xl font-coeliac font-semibold">Your Rights</h2>
                <ol start="19">
                    <li>
                        <p>
                            You have the right at any time to request access to all data we store on you, if you wish to
                            do so please put your request in writing to Coeliac Sanctuary, PO Box 643, Crewe, CW1 9LJ
                            and include your Name, Address, Phone Number and Email Address and we will endeavour to
                            provide you with any information we store about you within 1 month on receipt of your
                            request.
                        </p>
                    </li>
                    <li>
                        <p>
                            You have the right to be forgotten from our website and records, if you wish to do so please
                            put your request in writing to Coeliac Sanctuary, PO Box 643, Crewe, CW1 9LJ and include
                            your Name, Address, Phone Number and Email Address and we will endeavour to delete all
                            personal data we hold about you with the exception of any order invoices, which we legally
                            have to store for 7 (Seven) years.
                        </p>
                    </li>
                </ol>
            </div>
        </div>
    </div>
@endsection
