@extends('templates.page-single-column')

@section('primary-column')
    <div class="flex flex-col space-y-4">
        <div class="page-box text-sm space-y-4">
            <div class="main-body">
                <h1 class="text-2xl font-coeliac text-center font-semibold leading-tight md:text-left">
                    Privacy Policy
                </h1>

                <p>
                    Set out below is the Coeliac Sanctuary Privacy Policy, including what data we collect, why
                    we need it, how we use it and protect it, and how we remove it.
                </p>

                <ul>
                    <li>
                        <a href="#website">Coeliac Sanctuary Website</a>
                    </li>
                    <li>
                        <a href="#shop">Coeliac Sanctuary Shop</a>
                    </li>
                    <li>
                        <a href="#app">Coeliac Sanctuary - On the Go App</a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="page-box text-sm space-y-4">
            <div class="main-body">
                <ol class="text-sm space-y-2">
                    <li id="website" class="list-none">
                        <span class="text-lg font-semibold">
                            Coeliac Sanctuary Website
                        </span>
                        <ol>
                            <li>
                                All pages on the Coeliac Sanctuary website use Google Analytics to help us understand
                                how our visitors access and find the Coeliac Sanctuary website. Google Analytics uses
                                "Cookies", which are tiny text files placed on your device so the analytic software can
                                watch what pages you visit and how you got there, the analytics software only tracks
                                your activity on our own website, and does not track you elsewhere.
                            </li>
                            <li>
                                The information generated by the cookie is transmitted securely to Google's Servers
                                where they process it in a way so we can access it on the Google Analytics website, this
                                information Google store may include your IP address, but we do not get access to this
                                information, nor do we have any way to data to an actual person. For more information
                                please see the
                                <a title="Google Privacy Policy" href="https://policies.google.com/privacy"
                                   target="_blank">
                                    Google Analytics Privacy Policy
                                </a>.
                            </li>
                            <li>
                                All parts of the Coeliac Sanctuary website are protected by a SSL certificate, which
                                means all data is encrypted as it is transmitted from your browser to our server.
                            </li>
                            <li>
                                Depending on what parts of the website you use, data we may store about you includes,
                                but is not limited to;
                                <ol>
                                    <li>IP Address</li>
                                    <li>Name</li>
                                    <li>Email Address</li>
                                    <li>Postal Address</li>
                                    <li>Phone Number</li>
                                </ol>
                            </li>
                            <li>
                                For full information on why, how, and where we store your data please see the below
                                sections of this policy.
                            </li>
                            <li>
                                <span class="text-md font-semibold">
                                    Where to Eat Ratings
                                </span>
                                <ol>
                                    <li>
                                        Users have the ability to leave a rating of an eatery through our website.
                                    </li>
                                    <li>
                                        Users can leave an anonymous star rating without filling out their other
                                        details.
                                    </li>
                                    <li>
                                        If users wish to leave a more detailed rating they need to give their name,
                                        email address along with their review.
                                    </li>
                                    <li>
                                        Your email address is <strong>never</strong> displayed on the website or app,
                                        and is only used for validation purposes and spam protection.
                                    </li>
                                </ol>
                            </li>
                            <li>
                                <span class="text-md font-semibold">
                                    Advertisements
                                </span>
                                <ol>
                                    <li>
                                        Coeliac Sanctuary use Google AdSense to publish third party advertisements on
                                        our websites, we have no control over these ads, the content of them, or the
                                        third-party websites they link to. For more information please see the <a
                                            title="Google Privacy Policy" href="https://policies.google.com/privacy"
                                            target="_blank"> Google AdSense Privacy Policy </a>.
                                    </li>
                                </ol>
                            </li>
                            <li>
                                <span class="text-md font-semibold">
                                    Competitions
                                </span>
                                <ol>
                                    <li>
                                        During the course of a competition we store all data provided in our database,
                                        upon a competition ending all PERSONAL data will be securely removed after one
                                        month, we will however keep anonymised data so we can track the number of
                                        entrants in a competition, and in special cases where part of our competition is
                                        to leave feedback on the website, or suggest new features for the website, these
                                        will be kept as long as deemed necessary, but we will remove any personal
                                        information from the feedback or suggestions.
                                    </li>
                                </ol>
                            </li>
                            <li>
                                <span class="text-md font-semibold">
                                    Contact Forms
                                </span>
                                <ol>
                                    <li>
                                        All data through our contact forms is sent securely to our email address, once
                                        the matter has been dealt with the email is permanently deleted.
                                    </li>
                                </ol>
                            </li>
                            <li>
                                <span class="text-md font-semibold">
                                    Newsletter
                                </span>
                                <ol>
                                    <li>
                                        All users have the option to sign up to our free newsletter, you can do this
                                        through any page on our website, and you can also choose to do it through our
                                        competition pages and shop.
                                    </li>
                                    <li>
                                        The newsletter is strictly opt-in only, and you only need to provide your
                                        email, and you can-opt out at any time by pressing the Unsubscribe link at the
                                        bottom of each newsletter.
                                    </li>
                                </ol>
                            </li>
                            <li>
                                <span class="text-md font-semibold">
                                    Third Party Policies
                                </span>
                                <ol>
                                    <li>
                                        Websites linked from our website are out of our control and we are not
                                        responsible for any content, tracking or privacy policies on these websites or
                                        services.
                                    </li>
                                </ol>
                            </li>
                            <li>
                                <span class="text-md font-semibold">
                                    Your Rights
                                </span>
                                <ol>
                                    <li>
                                        You have the right at any time to request access to all data we store on you,
                                        if you wish to do so please put your request in writing to Coeliac Sanctuary, PO
                                        Box 643, Crewe, CW1 9LJ and include your Name, Address, Phone Number and Email
                                        Address and we will endeavour to provide you with any information we store about
                                        you within 1 month on receipt of your request.
                                    </li>
                                    <li>
                                        You have the right to be forgotten from our website and records, if you wish to
                                        do so please put your request in writing to Coeliac Sanctuary, PO Box 643,
                                        Crewe, CW1 9LJ and include your Name, Address, Phone Number and Email Address
                                        and we will endeavour to delete all personal data we hold about you with the
                                        exception of any order invoices, which we legally have to store for 7 (Seven)
                                        years.
                                    </li>
                                </ol>
                            </li>
                        </ol>
                    </li>
                </ol>
            </div>
        </div>

        <div class="page-box text-sm space-y-4">
            <div class="main-body">
                <ol class="text-sm space-y-2">
                    <li id="shop" class="list-none">
                        <span class="text-lg font-semibold">
                            Coeliac Sanctuary Shop
                        </span>
                        <ol>
                            <li>
                                Personal data is handled in several ways while using our online Shop
                            </li>
                            <li>
                                <span class="text-md font-semibold">
                                    Orders
                                </span>
                                <ol>
                                    <li>
                                        When you make an order in our online shop your name, email address and postal
                                        address are securely stored in our database, we will keep this data securely for
                                        at a minimum of seven (7) years for tax purposes. Your information is stored
                                        online in password protected environments and offline under lock and key. We do
                                        NOT, and never will store any payment information, including, but not limited
                                        to, Credit/Debit card numbers, Expiry dates, CVC numbers and PayPal usernames or
                                        Passwords.
                                    </li>
                                    <li>
                                        ALL payment processing is done through external servers (Stripe, Paypal) and
                                        your payment details do not get transmitted to our own server.
                                    </li>
                                </ol>
                            </li>
                            <li>
                                <span class="text-md font-semibold">
                                    Baskets
                                </span>
                                <ol>
                                    <li>
                                        When you store a temporary cookie on your device with your unique basket
                                        identifier, to link the open basket to your device.
                                    </li>
                                    <li>
                                        This cookie is deleted when you either complete an order, or after one hour of
                                        inactivity with our website.
                                    </li>
                                </ol>
                            </li>
                        </ol>
                    </li>
                </ol>
            </div>
        </div>

        <div class="page-box text-sm space-y-4">
            <div class="main-body">
                <ol class="text-sm space-y-2">
                    <li id="app" class="list-none">
                        <span class="text-lg font-semibold">
                            Coeliac Sanctuary - On the Go App
                        </span>
                        <ol>
                            <li>
                                <span class="text-md font-semibold">
                                    Your Location
                                </span>
                                <ol>
                                    <li>
                                        To show eateries around your location our app will get your current latitude and
                                        longitude and securely transmit it to our servers.
                                    </li>
                                    <li>
                                        We do not get any other data from you when getting your location.
                                    </li>
                                    <li>
                                        You can still use our app without having to give permission.
                                    </li>
                                </ol>
                            </li>
                            <li>
                                <span class="text-md font-semibold">
                                    Searching for Places
                                </span>
                                <ol>
                                    <li>
                                        When you search for a place in our app the text you entered is transmitted to
                                        our servers.
                                    </li>
                                    <li>
                                        We do not get any other data from you when you use the search functionality in
                                        our app.
                                    </li>
                                </ol>
                            </li>
                            <li>
                                <span class="text-md font-semibold">
                                    Analytics
                                </span>
                                <ol>
                                    <li>
                                        We use Google Firebase Analytics to track anonymous data on how people use our
                                        app.
                                    </li>
                                    <li>
                                        This includes the screens you view, locations opened, and links clicked.
                                    </li>
                                    <li>
                                        You can opt out of analytical tracking in the app by visiting the 'About' screen
                                        in the app, from the main app screen click the 3 lines icon in the top left,
                                        then click 'About'.
                                    </li>
                                </ol>
                            </li>
                            <li>
                                <span class="text-md font-semibold">
                                    Advertisements
                                </span>
                                <ol>
                                    <li>
                                        We use Google AdMob to display small banners on our app.
                                    </li>
                                    <li>
                                        This is the only advertisement in our app and is designed to be as unobtrusive
                                        as possible.
                                    </li>
                                </ol>
                            </li>
                            <li>
                                <span class="text-md font-semibold">
                                    Where to Eat Ratings
                                </span>
                                <ol>
                                    <li>
                                        Users have the ability to leave a rating of an eatery through our app, just like
                                        users can on our website.
                                    </li>
                                    <li>
                                        Users can leave an anonymous star rating without filling out their other
                                        details.
                                    </li>
                                    <li>
                                        If users wish to leave a more detailed rating they need to give their name,
                                        email address along with their review.
                                    </li>
                                    <li>
                                        Your email address is <strong>never</strong> displayed on the website or app,
                                        and is only used for validation purposes and spam protection.
                                    </li>
                                </ol>
                            </li>
                            <li>
                                <span class="text-md font-semibold">
                                    Contact Forms
                                </span>
                                <ol>
                                    <li>
                                        We have a series of forms through out the app where users can contact us. These
                                        include:
                                        <ol>
                                            <li>Recommend a place</li>
                                            <li>Report a place</li>
                                        </ol>
                                    </li>
                                    <li>
                                        These forms may ask for your name and email address along with the place
                                        information.
                                    </li>
                                    <li>
                                        Your email address is <strong>never</strong> displayed on the website or app,
                                        and is only used for validation purposes and spam protection.
                                    </li>
                                </ol>
                            </li>
                        </ol>
                    </li>
                </ol>
            </div>
        </div>
    </div>
@endsection
