<?php

declare(strict_types=1);

namespace Tests\Unit;

use Tests\Traits\HasImages;
use Coeliac\Common\Models\Image;
use Tests\Abstracts\RepositoryTest;
use Tests\Traits\Shop\CreateProduct;
use Tests\Traits\Shop\CreateVariant;
use Coeliac\Modules\Shop\ProductRepository;
use Coeliac\Modules\Shop\Models\ShopProduct;
use Coeliac\Common\Repositories\AbstractRepository;

class ShopProductRepositoryTest extends RepositoryTest
{
    use HasImages;
    use CreateProduct;
    use CreateVariant;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        foreach ($this->models as $model) {
            /* @var ShopProduct $model */
            $model->associateImage($this->makeImage(), Image::IMAGE_CATEGORY_SHOP_PRODUCT);
            $this->createVariant($model, ['live' => true]);
        }
    }

    protected function loadRepository(): AbstractRepository
    {
        return new ProductRepository();
    }

    protected function model(): string
    {
        return ShopProduct::class;
    }

    /** @test */
    public function it_has_the_images_included()
    {
        $this->models[0]->associateImage($this->makeImage(), Image::IMAGE_CATEGORY_SHOP_CATEGORY);

        $this->assertNotNull($this->repository->get(1)->images);
    }
}
