name: PHPUnit

on:
  push:
    paths:
      - '**.php'

jobs:
  phpunit:
    name: phpunit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Composer Dependencies
        uses: php-actions/composer@v6
        with:
          args: --ignore-platform-reqs
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

      - name: Run PHPUnit
        run: php artisan test --parallel
